[platformio]
default_envs = nano_new_bootloader
src_dir = .

[env:nano_new_bootloader]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_speed = 115200
upload_port = COM3

[env:nano_old_bootloader]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600
upload_port = COM3
